///////////////////////////////////////////////////////////////
/// These enumerations are mostly used for networking, used
/// to avoid having to add tons of network strings.
IGFORUMS_UPDATEPOSTCOUNT = 1
IGFORUMS_UPDATENAME = 2
IGFORUMS_SENDTHREAD = 3
IGFORUMS_SENDCATEGORY = 4
IGFORUMS_OPENFORUMS = 5
IGFORUMS_REQUESTICONS = 6
IGFORUMS_REQUESTUSERS = 7
IGFORUMS_INSERTUSER = 8
IGFORUMS_CREATECATEGORY = 9
IGFORUMS_REQUESTCATEGORY = 10
IGFORUMS_CREATETHREAD = 11
IGFORUMS_REQUESTTHREAD = 12
IGFORUMS_CREATEPOST = 13
IGFORUMS_UPDATERANK = 14
IGFORUMS_SETRANK = 15
IGFORUMS_DELETEALLPOSTS = 16
IGFORUMS_DELETEPOSTSBYID = 17
IGFORUMS_DELETETHREADSBYID = 18
IGFORUMS_DELETEPOST = 19
IGFORUMS_DELETEPOSTBYID = 20
IGFORUMS_REFRESHVIEWER = 21
IGFORUMS_DELETETHREAD = 22
IGFORUMS_DELETETHREADBYID = 23
IGFORUMS_TOGGLETHREADLOCK = 24
IGFORUMS_TOGGLETHREADSTICKY = 25
IGFORUMS_UPDATETHREADLOCK = 26
IGFORUMS_UPDATETHREADSTICKY = 27
IGFORUMS_UPDATEBAN = 28
IGFORUMS_BANUSER = 29
IGFORUMS_UNBANUSER = 30
IGFORUMS_SENDMESSAGE = 31
IGFORUMS_DELETECATEGORY = 32
IGFORUMS_REQUESTCATEGORIES = 33
IGFORUMS_CATEGORYMOVEUP = 34
IGFORUMS_CATEGORYMOVEDOWN = 35
IGFORUMS_SENDPAGEAMOUNT = 36
IGFORUMS_REQUESTLOGFILES = 37
IGFORUMS_SENDLOGFILENAME = 38
IGFORUMS_REQUESTLOGFILE = 39
IGFORUMS_SENDLOGFILEDATA = 40

///////////////////////////////////////////////////////////////
/// Used within the forums panel, tells the clear frame
/// content function what is being generated.
IGFORUMS_GENERATECATEGORIES = 1
IGFORUMS_GENERATETHREADS = 2
IGFORUMS_GENERATEPOSTS = 3